name: Windows Server ss

on:
  push:
    branches:
      - main

jobs:
  setup-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ runner.os }}-ngrok-server
      - name: Run Server Setup Container
        uses: docker/run-action@v2
        with:
          image: ${{ runner.os }}-ngrok-server
          command: |
            .\ngrok\ngrok.exe authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
            .\ngrok\ngrok.exe tcp --region ap 3389
            .\ngrok\ngrok.exe status > tunnel.txt
            for /F "tokens=3 delims= " %%a in ('type tunnel.txt ^| findstr "Forwarding"') do (
              set TUNNEL_URL=%%a
            )
            echo Public Tunnel URL: !TUNNEL_URL!
            echo Server successfully configured!
            echo.
            echo IP: %COMPUTERNAME%
            echo Username: administrator
            echo Password: ${{ secrets.ADMIN_PASSWORD }}
            echo.
            echo Please log in to your RDP using the tunnel URL: !TUNNEL_URL!
      - name: Cleanup
        run: docker stop $(docker ps -aq) && docker rm $(docker ps -aq)
