name: SSH Tunnel and RDP Access

on: [push, workflow_dispatch]

jobs:
  rdp-access:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup SSH Tunnel
        run: |
          ssh -N -f -R 3389:target_machine_ip:3389 user@target_machine_ip
      - name: Print RDP Access Instructions
        run: echo "Connect to the target machine using your RDP client at localhost:3389"
      - name: Wait for Connection (optional)
        run: timeout 10
      - name: Continue Workflow (if necessary)
        run: echo "Workflow continues after RDP connection established"
