name: SSH Access to Workflow Machine

on: [push, workflow_dispatch]

jobs:
  ssh-access:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Machine IP Address
        run: |
          # Get the public IP address of the workflow runner
          ip=$(curl -s https://ident.me)
          echo "::set-output name=ip::$ip"
          echo "::set-output name=hostname::$HOSTNAME"  # Get the machine hostname

      - name: Install OpenSSH Server
        run: sudo apt-get update && sudo apt-get install openssh-server -y

      - name: Generate SSH Key Pair
        run: |
          # Generate a new SSH key pair
          ssh-keygen -t rsa -b 4096 -N '' -f /tmp/workflow_key
          echo "::set-output name=public_key::$(cat /tmp/workflow_key.pub)"

      - name: Configure SSH Server
        run: |
          # Configure SSH server (change 'your_username' to your desired username)
          sudo sed -i 's/#Port 22/Port 2222/' /etc/ssh/sshd_config
