name: Advanced SSH Access Setup

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username for SSH access'
        required: true
        default: 'salehtl'
      client_public_key:
        description: 'Your public SSH key'
        required: false

jobs:
  ssh-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Server
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server

      - name: Configure SSH
        run: |
          sudo ssh-keygen -A  # Use sudo here
          sudo useradd ${{ inputs.username }}  # Use sudo
          sudo mkdir -p /home/${{ inputs.username }}/.ssh  # Use sudo
          sudo chown -R ${{ inputs.username }}:${{ inputs.username }} /home/${{ inputs.username }}/.ssh
          sudo chmod 700 /home/${{ inputs.username }}/.ssh

          echo "${{ inputs.client_public_key }}" | sudo tee -a /home/${{ inputs.username }}/.ssh/authorized_keys
          sudo chmod 600 /home/${{ inputs.username }}/.ssh/authorized_keys

          sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

      - name: Configure UFW (Adjust IP range as needed)
        run: |
          # Allow SSH only from your IP or a specific range. Replace with your IP or CIDR range.
          sudo ufw allow from 197.15.200.91 to any port 22 proto tcp
          sudo ufw enable

      # Option 1: Output IP address for direct connection (less secure, use with caution)
      - name: Get Runner IP (Use only if absolutely necessary)
        id: get_ip
        if: false # Disable by default.  Enable only if you understand the security implications.
        run: |
          echo "::set-output name=ip::$(dig +short myip.opendns.com @resolver1.opendns.com)"
        # ONLY use this if tmate is not feasible and you understand the security risks.

      # Option 2:  Tmate for secure, temporary SSH access (RECOMMENDED)
      - name: Setup tmate session (Recommended)
        uses: mxschmitt/action-tmate@v3
        if: ${{ ! github.event.inputs.client_public_key }}  # Use tmate if no public key provided
