name: Advanced SSH Access Setup

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username for SSH access'
        required: true
        default: 'salehtl'
      client_public_key:
        description: 'Your public SSH key'
        required: false

jobs:
  ssh-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Server
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server

      - name: Configure SSH
        run: |
          sudo ssh-keygen -A
          sudo useradd -m -s /bin/bash ${{ inputs.username }}
          sudo mkdir -p /home/${{ inputs.username }}/.ssh
          sudo chown -R ${{ inputs.username }}:${{ inputs.username }} /home/${{ inputs.username }}/.ssh
          sudo chmod 700 /home/${{ inputs.username }}/.ssh

          if [ -n "${{ inputs.client_public_key }}" ]; then
            echo "${{ inputs.client_public_key }}" | sudo tee /home/${{ inputs.username }}/.ssh/authorized_keys
            sudo chmod 600 /home/${{ inputs.username }}/.ssh/authorized_keys
          fi

          sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

      - name: Configure UFW
        run: |
          # Allow SSH only from your IP or a specific range. Replace with your IP or CIDR range.
          sudo ufw allow from 197.15.200.91 to any port 22 proto tcp
          sudo ufw enable

      - name: Display Hostname
        run: |
          echo "Hostname: $(hostname)"

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ ! github.event.inputs.client_public_key }}
```

You can now add this updated workflow to your repository to display the hostname of the current machine during the setup process.
